root.directory=./

ignore.directories=.git,.idea,node_lodules,target,out

ignore.extensions=.class,.jar,.png,.pdf,.zip

db.url=jdbc:postgresql://localhost:5432/search_engine
db.user=postgres
db.password=postgres1234
